import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#071407',
    overflow: 'hidden',
  },
  backgroundGlowTop: {
    position: 'absolute',
    top: -120,
    right: -120,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: 'rgba(94, 187, 82, 0.18)',
  },
  backgroundGlowBottom: {
    position: 'absolute',
    left: -140,
    bottom: -140,
    width: 360,
    height: 360,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 215, 0, 0.08)',
  },
  backgroundAccentLeft: {
    position: 'absolute',
    left: -40,
    top: '22%',
    width: 120,
    height: 300,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    transform: [{ rotate: '-18deg' }],
  },
  backgroundScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 20, 7, 0.36)',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 28,
  },
  pageShell: {
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 18,
  },
  pageShellWeb: {
    maxWidth: 760,
    paddingHorizontal: 14,
  },
  heroPanel: {
    padding: 28,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroLogoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 16,
  },
  logoCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: '#2D5A27',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  title: {
    fontSize: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 0.6,
  },
  subtitle: {
    fontSize: 14,
    color: '#D4DDCF',
    marginTop: 8,
    textAlign: 'center',
  },
  description: {
    fontSize: 14,
    lineHeight: 21,
    color: 'rgba(255, 255, 255, 0.78)',
    marginTop: 14,
    textAlign: 'center',
  },
  featureRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 18,
  },
  featurePill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(19, 50, 17, 0.62)',
    borderWidth: 1,
    borderColor: 'rgba(221, 245, 216, 0.18)',
  },
  featureText: {
    color: '#EAF4E4',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 8,
  },
  card: {
    backgroundColor: '#F6F8F4',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 12,
  },
  loginLabel: {
    fontSize: 22,
    fontWeight: '800',
    color: '#21401D',
    marginBottom: 18,
    textAlign: 'center',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#DDE6D8',
    borderRadius: 16,
    marginBottom: 14,
    paddingHorizontal: 14,
    height: 50,
    backgroundColor: '#FFFFFF',
  },
  icon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: '#21311F',
    fontSize: 16,
  },
  inlineErrorText: {
    color: '#A12626',
    backgroundColor: '#FCE8E8',
    borderWidth: 1,
    borderColor: '#F6C7C7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
    marginBottom: 2,
  },
  rememberContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  rememberLabelWrap: {
    flex: 1,
    paddingLeft: 12,
  },
  rememberLabel: {
    color: '#243B21',
    fontSize: 14,
    fontWeight: '700',
  },
  rememberHint: {
    color: '#667264',
    fontSize: 12,
    marginTop: 2,
  },
  loginButton: {
    backgroundColor: '#2D5A27',
    height: 50,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#1B3517',
    shadowOpacity: 0.25,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  loginButtonDisabled: {
    opacity: 0.72,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 1,
  },
  helperText: {
    color: '#667264',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 14,
  },
  registerLinkWrap: {
    marginTop: 10,
    alignSelf: 'center',
  },
  registerLinkText: {
    color: '#2D5A27',
    fontSize: 14,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  footer: {
    marginTop: 4,
    alignItems: 'center',
  },
  securityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
  },
  footerText: {
    color: '#FFF',
    fontSize: 12,
    marginLeft: 6,
  },
});
