export const assessmentQuestionBank = [
	{
		id: 'q1',
		type: 'mcq',
		topic: 'Conservation',
		question: 'What is the primary goal of habitat restoration?',
		options: ['Increase tourist numbers', 'Bring ecosystems back to healthy function', 'Build new roads', 'Reduce ranger patrols'],
	},
	{
		id: 'q2',
		type: 'mcq',
		topic: 'Conservation',
		question: 'Which action best helps prevent soil erosion on trails?',
		options: ['Removing all vegetation', 'Creating drainage and boardwalks where needed', 'Allowing off-trail biking', 'Using only concrete paths everywhere'],
	},
	{
		id: 'q3',
		type: 'mcq',
		topic: 'Conservation',
		question: 'A buffer zone around a protected area is used to:',
		options: ['Allow unrestricted hunting', 'Reduce external human pressure on core habitats', 'Increase light pollution', 'Store visitor parking only'],
	},
	{
		id: 'q4',
		type: 'mcq',
		topic: 'Conservation',
		question: 'Why is monitoring wildlife populations important?',
		options: ['For social media photos only', 'To detect ecosystem changes early', 'To reduce biodiversity reports', 'To replace field guides'],
	},
	{
		id: 'q5',
		type: 'mcq',
		topic: 'Conservation',
		question: 'Which is an example of in-situ conservation?',
		options: ['Seed bank storage', 'Zoo breeding program', 'Protecting species in their natural habitat', 'Laboratory tissue culture only'],
	},
	{
		id: 'q6',
		type: 'mcq',
		topic: 'Biodiversity',
		question: 'Biodiversity includes variation at which levels?',
		options: ['Genetic, species, and ecosystem levels', 'Only species level', 'Only ecosystem level', 'Only genetic level'],
	},
	{
		id: 'q7',
		type: 'mcq',
		topic: 'Biodiversity',
		question: 'An indicator species can help guides understand:',
		options: ['Ticket prices', 'Environmental health changes', 'Bus schedules', 'Trail paint color'],
	},
	{
		id: 'q8',
		type: 'mcq',
		topic: 'Biodiversity',
		question: 'Why are pollinators important in forest ecosystems?',
		options: ['They reduce seed production', 'They support plant reproduction and food webs', 'They increase invasive species spread only', 'They replace decomposers'],
	},
	{
		id: 'q9',
		type: 'mcq',
		topic: 'Biodiversity',
		question: 'What is a common risk of introducing invasive species?',
		options: ['Improved native habitat stability', 'Outcompeting native species', 'Lower ecosystem disturbance', 'Reduced management needs'],
	},
	{
		id: 'q10',
		type: 'mcq',
		topic: 'Biodiversity',
		question: 'A food web is useful because it shows:',
		options: ['Only top predators', 'Only herbivores', 'Relationships among many species in an ecosystem', 'Map directions for visitors'],
	},
	{
		id: 'q11',
		type: 'mcq',
		topic: 'Eco-tourism',
		question: 'A core principle of eco-tourism is to:',
		options: ['Maximize short-term visitor volume', 'Minimize environmental impact and support local communities', 'Remove all guide interpretation', 'Ignore carrying capacity'],
	},
	{
		id: 'q12',
		type: 'mcq',
		topic: 'Eco-tourism',
		question: 'What does carrying capacity refer to?',
		options: ['Maximum parking lot size', 'Number of visitors an area can sustain without damage', 'Guide backpack weight', 'Length of a trail'],
	},
	{
		id: 'q13',
		type: 'mcq',
		topic: 'Eco-tourism',
		question: 'Interpretive guiding contributes to eco-tourism by:',
		options: ['Encouraging wildlife feeding', 'Increasing visitor understanding and responsible behavior', 'Promoting noise in sensitive zones', 'Reducing local participation'],
	},
	{
		id: 'q14',
		type: 'mcq',
		topic: 'Eco-tourism',
		question: 'Which behavior should guides promote during nature walks?',
		options: ['Collecting plants as souvenirs', 'Staying on designated trails', 'Playing loud music', 'Approaching wildlife closely'],
	},
	{
		id: 'q15',
		type: 'mcq',
		topic: 'Eco-tourism',
		question: 'A local community benefit from eco-tourism can include:',
		options: ['Loss of cultural identity', 'Local employment and support for local products', 'Unmanaged waste growth', 'Restricted education access'],
	},
	{
		id: 'q16',
		type: 'mcq',
		topic: 'Legislation',
		question: 'Why should guides understand park regulations?',
		options: ['To ignore visitor complaints', 'To ensure activities comply with legal requirements', 'To replace all enforcement staff', 'To avoid safety briefings'],
	},
	{
		id: 'q17',
		type: 'mcq',
		topic: 'Legislation',
		question: 'Permits are commonly required for activities that:',
		options: ['Have no environmental impact', 'May affect protected zones or species', 'Are conducted at home', 'Only involve reading signage'],
	},
	{
		id: 'q18',
		type: 'mcq',
		topic: 'Legislation',
		question: 'If a visitor breaks park rules, a guide should first:',
		options: ['Ignore the behavior', 'Apply procedure: inform, de-escalate, and report according to policy', 'Argue loudly', 'Share personal opinions online'],
	},
	{
		id: 'q19',
		type: 'mcq',
		topic: 'Legislation',
		question: 'Wildlife protection laws generally prohibit:',
		options: ['Nature photography from distance', 'Harassment or illegal collection of protected species', 'Educational interpretation', 'Guided birdwatching'],
	},
	{
		id: 'q20',
		type: 'mcq',
		topic: 'Legislation',
		question: 'Incident reports are important because they:',
		options: ['Are optional paperwork only', 'Provide official records for management and legal follow-up', 'Replace emergency response', 'Can be submitted days later without details'],
	},
	{
		id: 'q21',
		type: 'mcq',
		topic: 'Safety',
		question: 'Before starting a guided hike, guides should prioritize:',
		options: ['Skipping briefings to save time', 'Weather checks, route risk review, and visitor briefing', 'Allowing anyone to lead the group', 'Removing emergency contacts'],
	},
	{
		id: 'q22',
		type: 'mcq',
		topic: 'Safety',
		question: 'The buddy system helps by:',
		options: ['Separating visitors widely', 'Improving accountability and rapid support', 'Reducing communication', 'Increasing response time'],
	},
	{
		id: 'q23',
		type: 'mcq',
		topic: 'Safety',
		question: 'If lightning risk increases, the safest action is to:',
		options: ['Continue on exposed ridges', 'Move group to safer shelter and suspend activity', 'Ask visitors to spread under tall trees', 'Wait without informing anyone'],
	},
	{
		id: 'q24',
		type: 'mcq',
		topic: 'Safety',
		question: 'A basic first-aid kit on guided tours should be:',
		options: ['Optional for short routes', 'Carried, checked, and restocked regularly', 'Kept only at headquarters', 'Used only for staff'],
	},
	{
		id: 'q25',
		type: 'mcq',
		topic: 'Safety',
		question: 'The most effective emergency communication approach is:',
		options: ['Unclear verbal messages', 'Predefined protocols and contact channels', 'Using personal social media first', 'Avoiding incident logs'],
	},
	{
		id: 'q26',
		type: 'fill',
		topic: 'Conservation',
		question: 'Fill in the blank: Conserving natural habitats helps protect ________ diversity.',
	},
	{
		id: 'q27',
		type: 'fill',
		topic: 'Biodiversity',
		question: 'Fill in the blank: Species that are not native and cause harm are called ________ species.',
	},
	{
		id: 'q28',
		type: 'fill',
		topic: 'Eco-tourism',
		question: 'Fill in the blank: Eco-tourism should create positive benefits for local ________.',
	},
	{
		id: 'q29',
		type: 'fill',
		topic: 'Legislation',
		question: 'Fill in the blank: Park guides must follow official ________ and regulations during tours.',
	},
	{
		id: 'q30',
		type: 'fill',
		topic: 'Safety',
		question: 'Fill in the blank: In an emergency, the first priority is visitor ________.',
	},
];

export const assessmentTopics = ['Conservation', 'Biodiversity', 'Eco-tourism', 'Legislation', 'Safety'];

export const defaultAssessmentDurationSeconds = 2 * 60 * 60;

export function buildAssessmentQuestions() {
	return assessmentQuestionBank.map((question) => ({
		...question,
		options: Array.isArray(question.options) ? [...question.options] : [],
	}));
}